version: "3.9"


services:
  tigerbeetle_0:
    image: ghcr.io/tigerbeetle/tigerbeetle
    command: "start --addresses=0.0.0.0:3001,0.0.0.0:3002,0.0.0.0:3003 /data/0_0.tigerbeetle"
    network_mode: host
    cap_add:       # HERE2
      - IPC_LOCK   # HERE
    volumes:
      - ./data:/data
    security_opt:
      - "seccomp=unconfined"
